### ISSUE TITLE
webhook signature validation spuriously fails

### ISSUE THREAD

**Issue by MartinNowak** [Dicebot/dlangci#27]
For quite a few PRs github shows that it got a 400 response with a signature mismatch.
`Provided signature [e6a7a2d4f9d5c65873795035a9bfcda0b90c14d5] did not match to calculated`

**Comment by MartinNowak** [comment]
Fixed by switching all hooks to application/json.

**Comment by MartinNowak** [comment]
Tracked it down to https://github.com/jenkinsci/github-plugin/pull/134#issuecomment-284171961.

**Comment by mirekphd** [comment]
@MartinNowak This bug in Jenkins Github Plugin you tracked down in 2017 is still there in 2023. It happens to me after each internet domain change (e.g. from .com to .org) in the Payload URL field on Github's `Webhooks > Manage webhook` page. 

But your workaround from 5 years ago is still valid. 

Yes, things are sometimes moving very slow indeed when it comes to fixing bugs in open source...

**Comment by mirekphd** [comment]
@MartinNowak This bug in Jenkins Github Plugin you tracked down in 2017 is still there in 2023. It happens to me after each internet domain change (e.g. from .com to .org) in the Payload URL field on Github's `Webhooks > Manage webhook` page. 

But your workaround from 5 years ago is still valid. 

Yes, things are sometimes moving very slow indeed when it comes to fixing bugs in open source...
